### ISSUE TITLE
Github workflow CI to cater builds for different OS versions

### ISSUE THREAD

**Issue by DieHard073055** [DeFiCh/metachain#62]
#### What would you like to be added:
As per title

#### Why is this needed:
In order to make sure our binaries are able to run on all the environments that we expect. Our builds should target all those environments.

[Reference Conversation](https://github.com/DeFiCh/metachain/pull/43#discussion_r959349664)

**Comment by DieHard073055** [comment]
What environments do we want to target ?

**Comment by fuxingloh** [comment]
> What environments do we want to target ?

Can you recommend some reasonable defaults?
